Refine periphery scan config with app+extension target, excluding MastodonSDK targets
- Found that periphery cannot scan MastodonSDK directly because of assumed macOS compatibility
	- Defaults to macOS 10.3, minimum is macOS 12.0, corresponding iOS 18 == macOS 15 suggested
- Skipping MastodonSDK is imperfect but lets us move forward

Tried to restrict XLPagerTabStript to iOS for periphery compatibility, but found that

1. When Periphery tries to build MastodonSDK support for macOS is assumed at 10.3
> Error message: error: The package product 'FaviconFinder' requires minimum platform version 12.0 for the macOS platform, but this target supports 10.13 (in target 'MastodonUI' from project 'MastodonSDK')
error: The package product 'FaviconFinder' requires minimum platform version 12.0 for the macOS platform, but this target supports 10.13 (in target 'MastodonSDKDynamic' from project 'MastodonSDK')

2.
Simply adding platforms: [.macOS("12.0")] to the Package.swift fails with
> Error: Shell command 'xcodebuild -project "/Users/jack/dev/mastodon-ios/Mastodon.xcodeproj" -scheme "MastodonSDK" -parallelizeTargets -derivedDataPath '/Users/jack/Library/Caches/com.github.peripheryapp/DerivedData-d255d8f2-cb0447ca-6ac1a2b3' -quiet build-for-testing CODE_SIGNING_ALLOWED="NO" ENABLE_BITCODE="NO" DEBUG_INFORMATION_FORMAT="dwarf" COMPILER_INDEX_STORE_ENABLE="YES" INDEX_ENABLE_DATA_STORE="YES"' returned exit status '65':
> /* com.apple.ibtool.errors */
> /Users/jack/Library/Caches/com.github.peripheryapp/DerivedData-d255d8f2-cb0447ca-6ac1a2b3/SourcePackages/checkouts/XLPagerTabStrip/Sources/XLPagerTabStrip/Resources/ButtonCell.xib: error: iOS xibs do not support target device type "mac".